---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "snppileup"
description: Calculate snp pileups from a bam pair
keywords:
  - snp
  - pileup
  - bams
tools:
  - "htstools":
      description: "Contains tools to process bam files for downstream copy number analysis."
      homepage: "https://github.com/mskcc/htstools"
      documentation: "https://github.com/mskcc/htstools"
      tool_dev_url: ""
      doi: ""
      licence:

input:
  - normal:
      type: list
      description: |
        Groovy Map containing sample information
        followed by the normal bam and index
        e.g. `[ id:'pair_id', file(normal.bam), file(normal.bai) ]`
  - tumor:
      type: list
      description: |
        Groovy Map containing sample information
        followed by the tumor bam and index
        e.g. `[ id:'pair_id', file(tumor.bam), file(tumor.bai) ]`
  - dbsnp:
      type: list
      description: |
        Groovy Map containing sample information
        followed by a vcf NCBI provided database vcf file 
        on genetic variation and the correspoding index
        e.g. `[ id:'pair_id', file(dbsnp.vcf.gz), file(dbsnp.vcf.gz.tbi) ]`

output:
  - pileup:
      type: list
      description: |
        Groovy Map containing sample information
        followed by the pileup file
        e.g. `[ id:'pair_id', file(pair_id.snp_pileup.gz) ]`

  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@nikhil"
maintainers:
  - "@nikhil"
