---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "snppileup"
description: Calculate snp pileups from a bam pair
keywords:
  - snp
  - pileup
  - bams
tools:
  - "htstools":
      description: "Contains tools to process bam files for downstream copy number analysis."
      homepage: "https://github.com/mskcc/htstools"
      documentation: "https://github.com/mskcc/htstools"
      tool_dev_url: ""
      doi: ""
      licence:

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'pair_id' ]`
  - normal_bam:
      type: file
      description: "The bam of the normal sample"
      pattern: "*.bam"
  - normal_bai:
      type: file
      description: "The bam index of the normal sample"
      pattern: "*.bai"
  - tumor_bam:
      type: file
      description: "The bam of the tumor sample"
      pattern: "*.bam"
  - tumor_bai:
      type: file
      description: "The bam index of the tumor sample"
      pattern: "*.bai"
  - dbsnp:
      type: file
      descrption: A NCBI provided database on genetic variation
      pattern:

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'pair_id' ]`

  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

  - pileup:
      type: file
      description: snppileup file
      pattern: "*.snp_pileup.gz"

authors:
  - "@nikhil"
maintainers:
  - "@nikhil"
