# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "traceback"
description: Genotype access and/or impact bams by a concatenated list of mafs. If patient ids are provided, access and/or impact bams are genotyped by concatenated mafs with matching patient ids.
keywords:
  - maf
  - bam
  - traceback
  - impact
  - access
  - genotyping
components:
  - genotypevariants/all
  - pvmaf/concat
  - pvmaf/tag

input:
  - bams:
      type: file
      description: |
        The input channel containing impact or access bams files
        Structure: 
        [[patient:null, id:'sample'], standard.bam, standard.bam.bai, [], [], [], []]
        or 
        [[patient:null, id:'sample'], [], [], duplex.bam, duplex.bam.bai, simplex.bam, simplex.bam.bai]
      pattern: "*.{bam/cram/sam}"
  - mafs:
      type: file
      description: |
        The input channel containing maf files
        Structure: // channel: [[patient:null], [maf1,...,maf2] ]
      pattern: "*.{maf,txt,tsv}"
  - fasta:
      description: |
        A channel containing the reference FASTA file
        Structure: [ path(fasta) ]
      pattern: "*.{fasta,fa}"
  - fai:
      description: |
        A channel containing the index of the reference FASTA file
        Structure: [ path(fai) ]
      pattern: "*.{fai}"
output:
  - maf:
      type: file
      description: |
        Channel containing genotyped Maf file
        Structure: [ val(meta), path(maf) ]
      pattern: "*.maf"
  - versions:
      type: file
      description: |
        File containing software versions
        Structure: [ path(versions.yml) ]
      pattern: "versions.yml"
authors:
  - "@buehlere"
maintainers:
  - "@buehlere"
