---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "mutect1"

description: This module utilizes version 1.1.5 of MuTect software to create Variant Call Format files from two sample BAMS.
keywords:
  - VCF
  - paired_samples
  - genomics
  - snps_and_indels

tools:
  - "mutect1":
      description: "This module utilizes version 1.1.5 of MuTect software to create Variant Call Format files from two sample BAMS."
      homepage: "https://github.com/mskcc-omics-workflows/modules"
      documentation: "https://github.com/msk-access/mutect1/blob/master/README.md"

input:
  
  - meta1:
      type: string
      description: |
        String variable containing control_sample_name (taken from pipeline input samplesheet)
        e.g. `Myeloid200-1`
  
  - meta2:
      type: string
      description: |
        String variable containing control_sample_name (taken from pipeline input samplesheet)
        e.g. `Myeloid200-2`
  
  - control_bam:
      type: file
      description: Input Control Sample associated BAM file (taken from pipeline input samplesheet)
      pattern: "*.{bam}"

  - case_bam:
      type: file
      description: Input Case Sample associated BAM file (taken from pipeline input samplesheet)
      pattern: "*.{bam}"

  - control_bai:
      type: file
      description: Input Control Sample associated BAM index file (taken from pipeline input samplesheet)
      pattern: "*.{bai}"

  - case_bai:
      type: file
      description: Input Case Sample associated BAM index file (taken from pipeline input samplesheet)
      pattern: "*.{bai}"

  - bed_file:
      type: file
      description: Input Standard BED File (taken from pipeline input samplesheet)
      pattern: "*.{bed}"

  - fasta_file:
      type: file
      description: Input Genome Fasta File (taken from pipeline input samplesheet)
      pattern: "*.{fasta}"

  - fasta_file:
      type: file
      description: Input Genome Fasta Index File (taken from pipeline input samplesheet)
      pattern: "*.{fasta.fai}"

output:
  
  - meta1:
      type: string
      description: |
        String variable containing control_sample_name (taken from pipeline input samplesheet)
        e.g. `Myeloid200-1`
  
  - meta2:
      type: string
      description: |
        String variable containing control_sample_name (taken from pipeline input samplesheet)
        e.g. `Myeloid200-2`

  - variantfile:
      type: file
      description: |
      output Variant Call Format File generated by MuTect 1.1.5 software
      pattern: "*.{mutect.vcf}"

  - stdmutectoutput:
      type: file
      description: |
      Standard text output file generated by MuTect 1.1.5 software
      pattern: "*.{mutect.txt}"

  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@rnaidu"
maintainers:
  - "@rnaidu"