name: "msisensor_ct_msi"
description: msisensor-ct detection of MSI regions.
keywords:
  - msisensor-ct
  - msi
tools:
  - "msisensor_ct":
      description: "MSIsensor-ct microsatellite instability detection using cfDNA sequencing data."
      homepage: "https://github.com/niu-lab/msisensor-ct"
      documentation: "https://github.com/niu-lab/msisensor-ct/blob/master/README.md"
      tool_dev_url: "https://github.com/msk-access/msisensor-ct"

      licence: ["Custom Licence"]

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - tumor_bam:
      type: file
      description: BAM/CRAM/SAM file
      pattern: "*.{bam,cram,sam}"
  - normal_bam:
      type: file
      description: BAM/CRAM/SAM file
      pattern: "*.{bam,cram,sam}"
  - intervals:
      type: file
      description: BED
      pattern: "*.bed"
  - models:
      type: file
      description: Folder of MSISensor-ct models (available from Github or as a product of msisensor-ct/scan)
      pattern: "*/*"
  - ctdna:
      type: boolean
      description: activate processing for ctDNA samples

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - msi:
      type: file
      description: MSI classifications as a text file
  - distribution:
      type: file
      description: Read count distributions of MSI regions
  - somatic:
      type: file
      description: Somatic MSI regions detected.
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "charalk@mskcc.org"