# This is a basic workflow to help you get started with Actions

name: Meta Yaml to MD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "feature/sync-gitbook", "develop" ]
  pull_request:
    branches: [ "feature/sync-gitbook", "develop" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  new_module:
    name: new module
    if: ${{ contains( github.event.head_commit.message, 'Module:') }}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed
      - uses: actions/checkout@v4
        with:
          ref: docs
      - name: Split branch name
        env:
          MODULE: ${{github.event.head_commit.message}}
        id: split
        run: echo "::set-output name=fragment::${MODULE##*:}"
      - name: Rename md file
        id: replace_slash
        run: |
          MD_NAME=${steps.split.outputs.fragment//\//_}"
          echo MD_NAME=${MD_NAME} >> $GITHUB_ENV
          echo ${MD_NAME}
      - name: Download convertor from yml to md
        run: |
          curl -o ${{ github.workspace }}/yaml_to_md.py https://raw.githubusercontent.com/mskcc-omics-workflows/yaml_to_md/0.0.1/yaml_to_md.py
          curl -o ${{ github.workspace }}/requirements.txt https://raw.githubusercontent.com/mskcc-omics-workflows/yaml_to_md/0.0.1/requirements.txt
      - name: Give convertor permissions
        run: chmod +x yaml_to_md.py
      - name: Install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r ${{ github.workspace }}/requirements.txt
      - uses: jaywcjlove/github-action-read-file@main
        id: cat_file_module
        with:
          branch: develop
          path: modules/msk/${{ steps.split.outputs.fragment }}/meta.yml
      - name: Run convertor to verify only for new module
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          echo '${{ steps.cat_file_module.outputs.content }}' > ${{ github.workspace }}/temp.yml
          python ${{ github.workspace }}/yaml_to_md.py validate --yaml-file ${{ github.workspace }}/temp.yml
      - name: Run convertor to generate md file for new module
        if: ${{ github.event_name == 'push' }}
        run: |
          echo '${{ steps.cat_file_module.outputs.content }}' > ${{ github.workspace }}/temp.yml
          python ${{ github.workspace }}/yaml_to_md.py all --yaml-file ${{ github.workspace }}/temp.yml --output-file ./modules/${{ env.MD_NAME }}.md
      - name: Check file existence for modules
        id: check_module_files
        uses: andstor/file-existence-action@v1
        with:
          files: modules/${{ steps.split.outputs.fragment }}.md
      - name: Add to SUMMARY for modules
        if: ${{ github.event_name == 'push'  && steps.check_module_files.outputs.files_exists == 'true' }}
        run: |
          curl -o ${{ github.workspace }}/update_summary.py https://raw.githubusercontent.com/mskcc-omics-workflows/modules/feature/sync-gitbook/.github/workflows/update_summary.py
          python ${{ github.workspace }}/update_summary.py SUMMARY.md "* [${{ env.MD_NAME }}](modules/${{ env.MD_NAME }}.md)" module > tmp_summary.md
          mv tmp_summary.md SUMMARY.md
      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "add doc for ${{ steps.split.outputs.fragment }}"
          add: '*/*.md --force'
          cwd: './'
      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "update summary for ${{ steps.split.outputs.fragment }}"
          add: 'SUMMARY.md --force'
          cwd: './'
  new_subworkflow:
    name: new subworkflow
    if: ${{ contains( github.event.head_commit.message, 'Subworkflow:') }}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
  
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed
      - uses: actions/checkout@v4
        with:
          ref: docs
      - name: Split branch name
        env:
          MODULE: ${{github.event.head_commit.message}}
        id: split
        run: echo "::set-output name=fragment::${SUBWORKFLOW##*:}"
      - name: Download convertor from yml to md
        run: |
          curl -o ${{ github.workspace }}/yaml_to_md.py https://raw.githubusercontent.com/mskcc-omics-workflows/yaml_to_md/0.0.1/yaml_to_md.py
          curl -o ${{ github.workspace }}/requirements.txt https://raw.githubusercontent.com/mskcc-omics-workflows/yaml_to_md/0.0.1/requirements.txt
      - name: Give convertor permissions
        run: chmod +x yaml_to_md.py
      - name: Install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r ${{ github.workspace }}/requirements.txt
      - uses: jaywcjlove/github-action-read-file@main
        id: cat_file_subworkflow
        with:
          branch: develop
          path: subworkflows/msk/${{ steps.split.outputs.fragment }}/meta.yml
      - name: Run convertor to verify only for new subworkflow
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          echo '${{ steps.cat_file_subworkflow.outputs.content }}' > ${{ github.workspace }}/temp.yml
          python ${{ github.workspace }}/yaml_to_md.py validate --yaml-file ${{ github.workspace }}/temp.yml
      - name: Run convertor to generate md file for new subworkflow
        if: ${{ github.event_name == 'push' }}
        run: |
          echo '${{ steps.cat_file_subworkflow.outputs.content }}' > ${{ github.workspace }}/temp.yml
          python ${{ github.workspace }}/yaml_to_md.py all --yaml-file ${{ github.workspace }}/temp.yml --output-file ./subworkflows/${{ steps.split.outputs.fragment }}.md
      - name: Check file existence for subworkflows
        id: check_subworkflow_files
        uses: andstor/file-existence-action@v1
        with:
          files: subworkflows/${{ steps.split.outputs.fragment }}.md
      - name: Add to SUMMARY for subworkflows
        if: ${{ github.event_name == 'push' && steps.check_subworkflow_files.outputs.files_exists == 'false' }}
        run: |
          curl -o ${{ github.workspace }}/update_summary.py https://raw.githubusercontent.com/mskcc-omics-workflows/modules/feature/sync-gitbook/.github/workflows/update_summary.py
          python ${{ github.workspace }}/update_summary.py SUMMARY.md "* [${{ steps.split.outputs.fragment }}](subworkflows/${{ steps.split.outputs.fragment }}.md)" subworkflow > tmp_summary.md
          mv tmp_summary.md SUMMARY.md
      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "add doc for ${{ steps.split.outputs.fragment }}"
          add: '*/*.md --force'
          cwd: './'
      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "update summary for ${{ steps.split.outputs.fragment }}"
          add: 'SUMMARY.md --force'
          cwd: './'
