name: Generate Code Owners
# Controls when the workflow will run
on:
    # Triggers the workflow on push or pull request events but only for the "main" branch
    push:
      branches: [ "feature/prs" ]
    pull_request:
      branches: [ "feature/prs" ]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    generate_owners:
        runs-on: ubuntu-latest
        steps:
          - name: Check out repository
            uses: actions/checkout@v4
          - name: Run Generate Owner's Script
            run: |
                chmod +x ./.github/generate_codeowners.sh
                ./.github/generate_codeowners.sh
          - uses: EndBug/add-and-commit@v9
            with:
                default_author: github_actions
                message: "add codeowners"
                add: 'CODEOWNERS* --force'
                cwd: './.github/'
